fbone/user/views.py
# -*- coding: utf-8 -*-

import os

from flask import Blueprint, render_template, send_from_directory, abort
from flask import current_app as APP
from flask.ext.login import login_required, current_user

from .models import User


user = Blueprint('user', __name__, url_prefix='/user')


@user.route('/')
@login_required
def index():
    if not current_user.is_authenticated():
        abort(403)
    return render_template('user/index.html', user=current_user)


@user.route('/<int:user_id>/profile')
def profile(user_id):
    user = User.get_by_id(user_id)
    return render_template('user/profile.html', user=user)


@user.route('/<int:user_id>/avatar/<path:filename>')
@login_required
def avatar(user_id, filename):
    dir_path = os.path.join(APP.config['UPLOAD_FOLDER'], 'user_%s' % user_id)
    return send_from_directory(dir_path, filename, as_attachment=True)

fbone/templates/macros/_ask_user_to_update_ie.html
<!--[if lt IE 7]>
    <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->

fbone/templates/macros/_form.html
{% macro render_checkbox(field) %}
<div class="checkbox{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id }}">
        {{ field }}{{ field.label.text }}
    </label>
    <span class="help-inline">{{ field.description }}</span>
    {% if field.errors -%}
    <ul class="help-block">
        {% for error in field.errors -%}
        <li>{{ error|e }}</li>
        {%- endfor %}
    </ul>
    {%- endif %}
</div>
{% endmacro%}

{% macro render_radio(field) %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    {{ field.label(class_="control-label") }}
    <div class="">
        {% for subfield in field -%}
        <label for="{{ subfield.id }}" class="radio-inline">
            {{ subfield }} {{ subfield.label.text }}
        </label>
        {%- endfor %}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
        <ul class="help-block">
            {% for error in field.errors -%}
            <li>{{ error }}</li>
            {%- endfor %}
        </ul>
        {%- endif %}
    </div>
</div>
{% endmacro %}

{% macro render_datepicker(field) %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label class="control-label" 
        for="{{ field.id }}">
        {{ field.label }}
    </label>
    <div class="">
        {{ field() }}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
        <ul class="help-block">
            {% for error in field.errors -%}
            <li>{{ error }}</li>
            {%- endfor %}
        </ul>
        {%- endif %}
    </div>
</div>
{% endmacro %}

{% macro render_textarea(field) %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label class="control-label" 
        for="{{ field.id }}">
        {{ field.label }}
    </label>
    <div class="">
        {{ field(class_="form-control", rows="4") }}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
        <ul class="help-block">
            {% for error in field.errors -%}
            <li>{{ error }}</li>
            {%- endfor %}
        </ul>
        {%- endif %}
    </div>
</div>
{% endmacro %}

{% macro render_file(field) %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label class="control-label" 
        for="{{ field.id }}">
        {{ field.label }}
    </label>
    <div class="">
        {{ field }}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
        <ul class="help-block">
            {% for error in field.errors -%}
            <li>{{ error }}</li>
            {%- endfor %}
        </ul>
        {%- endif %}
    </div>
</div>
{% endmacro %}

{% macro render_input(field) %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label class="control-label" 
        for="{{ field.id }}">
        {{ field.label }}
    </label>
    <div class="">
        {{ field(class_="form-control") }}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
        <ul class="help-block">
            {% for error in field.errors -%}
            <span class="help-block error">{{ error }}</span>
            {%- endfor %}
        </ul>
        {%- endif %}
    </div>
</div>
{% endmacro %}

{% macro render_action(field) %}
<div class="form-group">
    <div class="form-actions">
        {{ field(class_="btn btn-primary") }}
    </div>
</div>
{% endmacro %}

{% macro render_form(url, form, horizontal=False, legend=None, confirm_msg=None, formid=None) %}
{% set idattr = "id=" + formid if formid else "" %}
<form {{idattr}} class="{% if horizontal %}form-horizontal{% endif %}" method="POST" action="{{ url }}"
    {% if confirm_msg %}onsubmit='return confirm("{{ confirm_msg }}");' {% endif %} 
    {% if form.multipart %}enctype="multipart/form-data"{% endif %} >
    {{ form.hidden_tag() }}
        {% if legend %}
        <legend>{{ legend|safe }}</legend>
        {% endif %}
        {% set focus = True %}
        {% for field in form %}
            {% if field.type != "HiddenField" and field.type != "CSRFTokenField" %}
                {% if field.type == "RadioField" %}
                    {{ render_radio(field) }}
                {% elif field.type == "BooleanField" %}
                    {{ render_checkbox(field) }}
                {% elif field.type == "SubmitField" %}
                    {{ render_action(field) }}
                {% elif field.type == "TextAreaField" %}
                    {{ render_textarea(field) }}
                {% elif field.type == "DateField" %}
                    {{ render_datepicker(field) }}
                {% elif field.type == "FileField" %}
                    {{ render_file(field) }}
                {% elif field.type == "TextField" %}
                    {% if focus %}
                        {{ render_input(field) }}
                        {% set focus = False %}
                    {% else %}
                        {{ render_input(field) }}
                    {% endif %}
                {% else %}
                    {{ render_input(field) }}
                {% endif %}
            {% endif %}
        {% endfor %}
</form>
{% endmacro %}

fbone/templates/macros/_google_analytics.html
<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
    (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
    function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
    e=o.createElement(i);r=o.getElementsByTagName(i)[0];
    e.src='//www.google-analytics.com/analytics.js';
    r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
    ga('create','UA-XXXXX-X');ga('send','pageview');
</script>

fbone/templates/macros/_misc.html
{% macro render_user_table(users, class='') %}
<table class='{{ class }}'>
    <thead>
        <tr>
            <td>#</td>
            <td>Username</td>
            <td>Email</td>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <td>{{ loop.index }}</td>
            <td><a href="{{ url_for('user.profile', name=user.name) }}">{{ user.name }}</a></td>
            <td>{{ user.email }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endmacro %}

{% macro render_pagination(pagination, endpoint) %}
    {% if pagination.pages > 1 %}
        <div class='pagination'>
            <ul>
                <li class="prev {% if not pagination.has_prev %}disabled{% endif %}"><a href="{{ url_for(endpoint, page=pagination.page-1) }}">&larr; Previous</a></li>
                {% for page in pagination.iter_pages() %}
                    {% if page %}
                        <li class='{% if page == pagination.page %}active{% endif %}'>
                            <a href='{{ url_for(endpoint, page=page) }}'>{{ page }}</a>
                        </li>
                    {% else %}
                        <li>
                            <a href='#'>...</a>
                        </li>
                    {% endif %}
                {% endfor %}
                <li class="next {% if not pagination.has_next %}disabled{% endif %}"><a href="{{ url_for(endpoint, page=pagination.page+1) }}">Next &rarr;</a></li>
            </ul>
        </div>
    {% endif %}
{% endmacro %}

fbone/templates/macros/_reset_password.html
<p>Forgot your password, {{ username }}?</p>

<p>{{ project }} received a request to reset the password for your {{ project }} account {{ username }}.</p>

<p>If you want to reset your password, click on the link below (or copy and paste the URL into your browser):</p>

<a href="{{ url }}">Click to Reset Password</a>

<p>This link takes you to a secure page where you can change your password. For tips on selecting a strong password, see our Safe Tweeting help page.</p>

<p>If you don't want to reset your password, please ignore this message. Your password will not be reset. If you have any concerns, please contact us at {{ project }} Support.</p>

<p>The {{ project }} Team</p>